export const SET_TOOLTIP_DATA = 'SET_TOOLTIP_DATA';
export const SET_TOOLTIP_VISIBILITY = 'SET_TOOLTIP_VISIBILITY';
export const SET_ACTIVE_CHROMOSOME = 'SET_ACTIVE_CHROMOSOME';
export const SET_ACTIVE_SUBGENOME = 'SET_ACTIVE_SUBGENOME';
export const SET_CHROMOSOME_DATA = 'SET_CHROMOSOME_DATA';
export const SET_GENOME_DATA = 'SET_GENOME_DATA';
export const SET_GENOME_VIEW_DATA = 'SET_GENOME_VIEW_DATA'
export const SET_REGION = 'SET_REGION';
export const SET_ACTIVE_GENES = 'SET_ACTIVE_GENES';
export const SET_HOVERED_GENE = 'SET_HOVERED_GENE';
export const SET_GENE_DATA = 'SET_GENE_DATA';
export const SET_GENOME_REGION = 'SET_GENOME_REGION';
export const SET_ALL_DEFAULTS ='SET_ALL_DEFAULTS';
export const SET_USER_NAME = 'SET_USER_NAME';
export const SET_ROOM_NAME = 'SET_ROOM_NAME';
export const SET_CONNECTION_STATUS = 'SET_CONNECTION_STATUS';


