export const SET_TOOLTIP_DATA = 'SET_TOOLTIP_DATA';
export const SET_TOOLTIP_VISIBILITY = 'SET_TOOLTIP_VISIBILITY';
export const SET_ACTIVE_CHROMOSOME = 'SET_ACTIVE_CHROMOSOME';
export const SET_ACTIVE_SUBGENOME = 'SET_ACTIVE_SUBGENOME';
export const SET_CHROMOSOME_DATA = 'SET_CHROMOSOME_DATA';
export const SET_GENOME_DATA = 'SET_GENOME_DATA';
export const SET_REGION = 'SET_REGION';

